[tools]
# Programming Languages
go = "latest"
node = "latest"
python = "latest"

# IaC
terraform = "latest"

# npm Packages
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

